Integrate GitHub api
SheW0lf/Tikit pull request #14
Opened 2021-10-13 18:05 UTC by bjoroen

- Added prettier
- Issues now comes from GitHub API

2021-10-17 03:21 UTC, SheW0lf requested changes
🎉 @bjoroen Nice job!! Just a small stylistic request, but this is awesome thanks!

2021-10-17 10:44 UTC, bjoroen commented
I have changed it so it only shows the date now

2021-10-18 00:20 UTC, SheW0lf reviewed
@bjoroen looks good! just a couple of merge conflicts to fix

2021-10-21 03:18 UTC, SheW0lf approved these changes

2021-10-21 03:18 UTC, merged